name: Reporte Diario Meta Ads

on:
  schedule:
    # 6:30 AM UTC-5 (Bogotá/Lima/Quito) = 11:30 AM UTC
    - cron: '30 11 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-report:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Create google_creds.json
        run: echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > google_creds.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

      - name: Run script
        env:
          ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: node index.js
